using System;
using System.Drawing;
using System.Collections;
using System.ComponentModel;
using System.Windows.Forms;

using ContactosDL;


namespace CRMContactos
{
    /// <summary>
    /// Summary description for Contacto.
    /// </summary>
    public class Contacto : System.Windows.Forms.Form
    {
        #region Autogenerated Code
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.TextBox txtNombre;
        private System.Windows.Forms.TextBox txtTitulo;
        private System.Windows.Forms.Label label6;
        private System.Windows.Forms.TextBox txtOrganizacion;
        private System.Windows.Forms.ComboBox cboPuesto;
        private System.Windows.Forms.Label label7;
        private System.Windows.Forms.TextBox txtObservaciones;
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.Container components = null;
        private System.Windows.Forms.Button btnAceptar;
        private System.Windows.Forms.Button btnCancelar;

        private System.Data.DataSet dsCatalogos;
        private System.Windows.Forms.Button btnModificar;
        private CRMContactos.Telefono telefono1;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.Label label9;
        private System.Windows.Forms.Label label10;
        private CRMContactos.TelefonoCelular telefonoCelular1;
        private CRMContactos.EMail eMail1;
        private System.Windows.Forms.Label label8;
        private System.Windows.Forms.Button btnClientesAsociados;
        private System.Windows.Forms.TextBox txtDomicilio;
        private System.Windows.Forms.Label label11;
        private System.Windows.Forms.DateTimePicker dtpFCumpleanios;
        private System.Windows.Forms.TextBox txtHorario;
        private System.Windows.Forms.DataGridTableStyle Contactos;
        private System.Windows.Forms.DataGridTextBoxColumn cCliente;
        private System.Windows.Forms.DataGridTextBoxColumn cNombre;
        private System.Windows.Forms.DataGrid grdCliente;
        private System.Windows.Forms.DataGridTextBoxColumn cTipoContacto;
        private System.Windows.Forms.ContextMenu contextMenu1;
        private System.Windows.Forms.MenuItem menuItem2;
        #endregion

        private cContacto _contacto;
        private bool _editable = false;
        private string _urlGateway;
        private byte _modulo;
        private string _cadenaConexion;

        public string UrlGateway
        {
            get
            {
                return _urlGateway;
            }

            set
            {
                _urlGateway = value;
            }
        }

        public byte Modulo
        {
            get
            {
                return _modulo;
            }

            set
            {
                _modulo = value;
            }
        }

        public string CadenaConexion
        {
            get
            {
                return _cadenaConexion;
            }

            set
            {
                _cadenaConexion = value;
            }
        }

        //Nuevos contactos
        public Contacto(System.Data.DataSet Catalogo)
		{
			//
			// Required for Windows Form Designer support
			//
			InitializeComponent();

			//
			// TODO: Add any constructor code after InitializeComponent call
			//
			dsCatalogos = Catalogo;
			_contacto = new cContacto();
			//
			//Handler de "Aceptar" para alta de contactos
			dataBindComboPuesto();
			cboPuesto.SelectedIndex = -1;
			
			this.cboPuesto.TextChanged += new System.EventHandler(this.cboPuesto_TextChanged);
			this.cboPuesto.Enter += new System.EventHandler(this.cboCalle_Enter);
			

			this.btnAceptar.Click += new System.EventHandler(this.btnAceptar_Click);
			activarParaEditar(false);
		}

		public Contacto(System.Data.DataSet Catalogo, int Contacto)
		{
			this.InitializeComponent();
			dsCatalogos = Catalogo;

			try
			{
				_contacto = new cContacto(Contacto);
				cargaDatos();
			}
			catch (Exception ex)
			{
				MessageBox.Show("Ha ocurrido un error:" + (char)13 + ex.ToString(), this.Text, MessageBoxButtons.OK, MessageBoxIcon.Error);
			}
			

			this.cboPuesto.TextChanged += new System.EventHandler(this.cboPuesto_TextChanged);
			this.cboPuesto.Enter += new System.EventHandler(this.cboCalle_Enter);
			this.btnAceptar.Click += new System.EventHandler(this.btnAceptar1_Click);
			activarParaEditar(true);
			
		}

		/// <summary>
		/// Clean up any resources being used.
		/// </summary>
		protected override void Dispose( bool disposing )
		{
			if( disposing )
			{
				if(components != null)
				{
					components.Dispose();
				}
			}
			base.Dispose( disposing );
		}

		#region Windows Form Designer generated code
		/// <summary>
		/// Required method for Designer support - do not modify
		/// the contents of this method with the code editor.
		/// </summary>
		private void InitializeComponent()
		{
			System.Resources.ResourceManager resources = new System.Resources.ResourceManager(typeof(Contacto));
			this.label1 = new System.Windows.Forms.Label();
			this.txtNombre = new System.Windows.Forms.TextBox();
			this.label2 = new System.Windows.Forms.Label();
			this.txtTitulo = new System.Windows.Forms.TextBox();
			this.txtObservaciones = new System.Windows.Forms.TextBox();
			this.label3 = new System.Windows.Forms.Label();
			this.label5 = new System.Windows.Forms.Label();
			this.label6 = new System.Windows.Forms.Label();
			this.txtOrganizacion = new System.Windows.Forms.TextBox();
			this.cboPuesto = new System.Windows.Forms.ComboBox();
			this.label7 = new System.Windows.Forms.Label();
			this.btnAceptar = new System.Windows.Forms.Button();
			this.btnCancelar = new System.Windows.Forms.Button();
			this.btnModificar = new System.Windows.Forms.Button();
			this.telefono1 = new CRMContactos.Telefono();
			this.label4 = new System.Windows.Forms.Label();
			this.label9 = new System.Windows.Forms.Label();
			this.txtDomicilio = new System.Windows.Forms.TextBox();
			this.label10 = new System.Windows.Forms.Label();
			this.telefonoCelular1 = new CRMContactos.TelefonoCelular();
			this.txtHorario = new System.Windows.Forms.TextBox();
			this.eMail1 = new CRMContactos.EMail();
			this.label8 = new System.Windows.Forms.Label();
			this.btnClientesAsociados = new System.Windows.Forms.Button();
			this.dtpFCumpleanios = new System.Windows.Forms.DateTimePicker();
			this.label11 = new System.Windows.Forms.Label();
			this.grdCliente = new System.Windows.Forms.DataGrid();
			this.contextMenu1 = new System.Windows.Forms.ContextMenu();
			this.menuItem2 = new System.Windows.Forms.MenuItem();
			this.Contactos = new System.Windows.Forms.DataGridTableStyle();
			this.cCliente = new System.Windows.Forms.DataGridTextBoxColumn();
			this.cNombre = new System.Windows.Forms.DataGridTextBoxColumn();
			this.cTipoContacto = new System.Windows.Forms.DataGridTextBoxColumn();
			((System.ComponentModel.ISupportInitialize)(this.grdCliente)).BeginInit();
			this.SuspendLayout();
			// 
			// label1
			// 
			this.label1.AutoSize = true;
			this.label1.Location = new System.Drawing.Point(8, 35);
			this.label1.Name = "label1";
			this.label1.Size = new System.Drawing.Size(48, 14);
			this.label1.TabIndex = 0;
			this.label1.Text = "Nombre:";
			// 
			// txtNombre
			// 
			this.txtNombre.CharacterCasing = System.Windows.Forms.CharacterCasing.Upper;
			this.txtNombre.Location = new System.Drawing.Point(116, 32);
			this.txtNombre.Name = "txtNombre";
			this.txtNombre.Size = new System.Drawing.Size(444, 21);
			this.txtNombre.TabIndex = 1;
			this.txtNombre.Tag = "required";
			this.txtNombre.Text = "";
			// 
			// label2
			// 
			this.label2.AutoSize = true;
			this.label2.Location = new System.Drawing.Point(8, 11);
			this.label2.Name = "label2";
			this.label2.Size = new System.Drawing.Size(36, 14);
			this.label2.TabIndex = 2;
			this.label2.Text = "Título:";
			// 
			// txtTitulo
			// 
			this.txtTitulo.CharacterCasing = System.Windows.Forms.CharacterCasing.Upper;
			this.txtTitulo.Location = new System.Drawing.Point(116, 8);
			this.txtTitulo.Name = "txtTitulo";
			this.txtTitulo.Size = new System.Drawing.Size(420, 21);
			this.txtTitulo.TabIndex = 0;
			this.txtTitulo.Text = "";
			// 
			// txtObservaciones
			// 
			this.txtObservaciones.Location = new System.Drawing.Point(116, 268);
			this.txtObservaciones.Multiline = true;
			this.txtObservaciones.Name = "txtObservaciones";
			this.txtObservaciones.Size = new System.Drawing.Size(444, 65);
			this.txtObservaciones.TabIndex = 9;
			this.txtObservaciones.Text = "";
			// 
			// label3
			// 
			this.label3.AutoSize = true;
			this.label3.Location = new System.Drawing.Point(8, 272);
			this.label3.Name = "label3";
			this.label3.Size = new System.Drawing.Size(80, 14);
			this.label3.TabIndex = 5;
			this.label3.Text = "Observaciones:";
			// 
			// label5
			// 
			this.label5.AutoSize = true;
			this.label5.Location = new System.Drawing.Point(8, 59);
			this.label5.Name = "label5";
			this.label5.Size = new System.Drawing.Size(42, 14);
			this.label5.TabIndex = 11;
			this.label5.Text = "Puesto:";
			// 
			// label6
			// 
			this.label6.AutoSize = true;
			this.label6.Location = new System.Drawing.Point(8, 83);
			this.label6.Name = "label6";
			this.label6.Size = new System.Drawing.Size(73, 14);
			this.label6.TabIndex = 13;
			this.label6.Text = "Organización:";
			// 
			// txtOrganizacion
			// 
			this.txtOrganizacion.CharacterCasing = System.Windows.Forms.CharacterCasing.Upper;
			this.txtOrganizacion.Location = new System.Drawing.Point(116, 80);
			this.txtOrganizacion.Name = "txtOrganizacion";
			this.txtOrganizacion.Size = new System.Drawing.Size(444, 21);
			this.txtOrganizacion.TabIndex = 3;
			this.txtOrganizacion.Tag = "required";
			this.txtOrganizacion.Text = "";
			// 
			// cboPuesto
			// 
			this.cboPuesto.Location = new System.Drawing.Point(116, 56);
			this.cboPuesto.Name = "cboPuesto";
			this.cboPuesto.Size = new System.Drawing.Size(444, 21);
			this.cboPuesto.TabIndex = 2;
			// 
			// label7
			// 
			this.label7.AutoSize = true;
			this.label7.Location = new System.Drawing.Point(8, 247);
			this.label7.Name = "label7";
			this.label7.Size = new System.Drawing.Size(45, 14);
			this.label7.TabIndex = 16;
			this.label7.Text = "Horario:";
			// 
			// btnAceptar
			// 
			this.btnAceptar.Image = ((System.Drawing.Bitmap)(resources.GetObject("btnAceptar.Image")));
			this.btnAceptar.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this.btnAceptar.Location = new System.Drawing.Point(576, 8);
			this.btnAceptar.Name = "btnAceptar";
			this.btnAceptar.TabIndex = 10;
			this.btnAceptar.Text = "    &Aceptar";
			// 
			// btnCancelar
			// 
			this.btnCancelar.Image = ((System.Drawing.Bitmap)(resources.GetObject("btnCancelar.Image")));
			this.btnCancelar.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this.btnCancelar.Location = new System.Drawing.Point(576, 36);
			this.btnCancelar.Name = "btnCancelar";
			this.btnCancelar.TabIndex = 11;
			this.btnCancelar.Text = "    &Cancelar";
			this.btnCancelar.Click += new System.EventHandler(this.btnCancelar_Click);
			// 
			// btnModificar
			// 
			this.btnModificar.Image = ((System.Drawing.Bitmap)(resources.GetObject("btnModificar.Image")));
			this.btnModificar.Location = new System.Drawing.Point(536, 8);
			this.btnModificar.Name = "btnModificar";
			this.btnModificar.Size = new System.Drawing.Size(24, 21);
			this.btnModificar.TabIndex = 12;
			this.btnModificar.Click += new System.EventHandler(this.btnModificar_Click);
			// 
			// telefono1
			// 
			this.telefono1.Extension = "";
			this.telefono1.Lada = "";
			this.telefono1.Location = new System.Drawing.Point(116, 172);
			this.telefono1.Name = "telefono1";
			this.telefono1.NumeroTelefono = "";
			this.telefono1.ReadOnly = false;
			this.telefono1.Size = new System.Drawing.Size(444, 21);
			this.telefono1.TabIndex = 5;
			this.telefono1.Tag = "required";
			// 
			// label4
			// 
			this.label4.AutoSize = true;
			this.label4.Location = new System.Drawing.Point(8, 175);
			this.label4.Name = "label4";
			this.label4.Size = new System.Drawing.Size(52, 14);
			this.label4.TabIndex = 28;
			this.label4.Text = "Teléfono:";
			// 
			// label9
			// 
			this.label9.AutoSize = true;
			this.label9.Location = new System.Drawing.Point(8, 199);
			this.label9.Name = "label9";
			this.label9.Size = new System.Drawing.Size(42, 14);
			this.label9.TabIndex = 29;
			this.label9.Text = "Celular:";
			// 
			// txtDomicilio
			// 
			this.txtDomicilio.CharacterCasing = System.Windows.Forms.CharacterCasing.Upper;
			this.txtDomicilio.Location = new System.Drawing.Point(116, 104);
			this.txtDomicilio.Multiline = true;
			this.txtDomicilio.Name = "txtDomicilio";
			this.txtDomicilio.Size = new System.Drawing.Size(444, 65);
			this.txtDomicilio.TabIndex = 4;
			this.txtDomicilio.Tag = "required";
			this.txtDomicilio.Text = "";
			// 
			// label10
			// 
			this.label10.AutoSize = true;
			this.label10.Location = new System.Drawing.Point(8, 108);
			this.label10.Name = "label10";
			this.label10.Size = new System.Drawing.Size(53, 14);
			this.label10.TabIndex = 32;
			this.label10.Text = "Domicilio:";
			// 
			// telefonoCelular1
			// 
			this.telefonoCelular1.Location = new System.Drawing.Point(116, 196);
			this.telefonoCelular1.Name = "telefonoCelular1";
			this.telefonoCelular1.ReadOnly = false;
			this.telefonoCelular1.Size = new System.Drawing.Size(444, 21);
			this.telefonoCelular1.TabIndex = 6;
			this.telefonoCelular1.Telefono = "";
			// 
			// txtHorario
			// 
			this.txtHorario.Location = new System.Drawing.Point(116, 244);
			this.txtHorario.Name = "txtHorario";
			this.txtHorario.Size = new System.Drawing.Size(220, 21);
			this.txtHorario.TabIndex = 8;
			this.txtHorario.Text = "";
			// 
			// eMail1
			// 
			this.eMail1.CorreoElectronico = "";
			this.eMail1.Location = new System.Drawing.Point(116, 220);
			this.eMail1.Name = "eMail1";
			this.eMail1.ReadOnly = false;
			this.eMail1.Size = new System.Drawing.Size(444, 21);
			this.eMail1.TabIndex = 7;
			this.eMail1.ValidatedMail += new System.EventHandler(this.eMail1_ValidatedMail);
			// 
			// label8
			// 
			this.label8.AutoSize = true;
			this.label8.Location = new System.Drawing.Point(8, 223);
			this.label8.Name = "label8";
			this.label8.Size = new System.Drawing.Size(99, 14);
			this.label8.TabIndex = 36;
			this.label8.Text = "Correo Electrónico:";
			// 
			// btnClientesAsociados
			// 
			this.btnClientesAsociados.Location = new System.Drawing.Point(4, 337);
			this.btnClientesAsociados.Name = "btnClientesAsociados";
			this.btnClientesAsociados.Size = new System.Drawing.Size(108, 20);
			this.btnClientesAsociados.TabIndex = 38;
			this.btnClientesAsociados.Text = "Clientes asociados:";
			this.btnClientesAsociados.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this.btnClientesAsociados.Click += new System.EventHandler(this.btnClientesAsociados_Click);
			// 
			// dtpFCumpleanios
			// 
			this.dtpFCumpleanios.Format = System.Windows.Forms.DateTimePickerFormat.Short;
			this.dtpFCumpleanios.Location = new System.Drawing.Point(464, 244);
			this.dtpFCumpleanios.Name = "dtpFCumpleanios";
			this.dtpFCumpleanios.Size = new System.Drawing.Size(96, 21);
			this.dtpFCumpleanios.TabIndex = 39;
			// 
			// label11
			// 
			this.label11.AutoSize = true;
			this.label11.Location = new System.Drawing.Point(344, 248);
			this.label11.Name = "label11";
			this.label11.Size = new System.Drawing.Size(116, 14);
			this.label11.TabIndex = 40;
			this.label11.Text = "Fecha de cumpleaños:";
			// 
			// grdCliente
			// 
			this.grdCliente.CaptionVisible = false;
			this.grdCliente.ContextMenu = this.contextMenu1;
			this.grdCliente.DataMember = "";
			this.grdCliente.HeaderForeColor = System.Drawing.SystemColors.ControlText;
			this.grdCliente.Location = new System.Drawing.Point(116, 336);
			this.grdCliente.Name = "grdCliente";
			this.grdCliente.ReadOnly = true;
			this.grdCliente.Size = new System.Drawing.Size(444, 92);
			this.grdCliente.TabIndex = 41;
			this.grdCliente.TableStyles.AddRange(new System.Windows.Forms.DataGridTableStyle[] {
																								   this.Contactos});
			this.grdCliente.Leave += new System.EventHandler(this.grdCliente_Leave);
			// 
			// contextMenu1
			// 
			this.contextMenu1.MenuItems.AddRange(new System.Windows.Forms.MenuItem[] {
																						 this.menuItem2});
			// 
			// menuItem2
			// 
			this.menuItem2.Index = 0;
			this.menuItem2.Text = "&Eliminar la relación seleccionada";
			this.menuItem2.Click += new System.EventHandler(this.menuItem2_Click);
			// 
			// Contactos
			// 
			this.Contactos.DataGrid = this.grdCliente;
			this.Contactos.GridColumnStyles.AddRange(new System.Windows.Forms.DataGridColumnStyle[] {
																										this.cCliente,
																										this.cNombre,
																										this.cTipoContacto});
			this.Contactos.HeaderForeColor = System.Drawing.SystemColors.ControlText;
			this.Contactos.MappingName = "ListaClientes";
			this.Contactos.ReadOnly = true;
			// 
			// cCliente
			// 
			this.cCliente.Format = "";
			this.cCliente.FormatInfo = null;
			this.cCliente.HeaderText = "Cliente";
			this.cCliente.MappingName = "Cliente";
			this.cCliente.NullText = "";
			this.cCliente.ReadOnly = true;
			this.cCliente.Width = 75;
			// 
			// cNombre
			// 
			this.cNombre.Format = "";
			this.cNombre.FormatInfo = null;
			this.cNombre.HeaderText = "Nombre";
			this.cNombre.MappingName = "Nombre";
			this.cNombre.NullText = "";
			this.cNombre.ReadOnly = true;
			this.cNombre.Width = 235;
			// 
			// cTipoContacto
			// 
			this.cTipoContacto.Format = "";
			this.cTipoContacto.FormatInfo = null;
			this.cTipoContacto.HeaderText = "Tipo de contacto";
			this.cTipoContacto.MappingName = "TipoContactoDescripcion";
			this.cTipoContacto.NullText = "";
			this.cTipoContacto.ReadOnly = true;
			this.cTipoContacto.Width = 94;
			// 
			// Contacto
			// 
			this.AutoScaleBaseSize = new System.Drawing.Size(5, 14);
			this.ClientSize = new System.Drawing.Size(658, 439);
			this.Controls.AddRange(new System.Windows.Forms.Control[] {
																		  this.label11,
																		  this.dtpFCumpleanios,
																		  this.btnClientesAsociados,
																		  this.label8,
																		  this.eMail1,
																		  this.txtHorario,
																		  this.telefonoCelular1,
																		  this.label10,
																		  this.label9,
																		  this.label4,
																		  this.label7,
																		  this.label6,
																		  this.label5,
																		  this.label3,
																		  this.label2,
																		  this.label1,
																		  this.txtDomicilio,
																		  this.telefono1,
																		  this.btnModificar,
																		  this.btnCancelar,
																		  this.btnAceptar,
																		  this.cboPuesto,
																		  this.txtOrganizacion,
																		  this.txtObservaciones,
																		  this.txtTitulo,
																		  this.txtNombre,
																		  this.grdCliente});
			this.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((System.Byte)(0)));
			this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
			this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
			this.MaximizeBox = false;
			this.MinimizeBox = false;
			this.Name = "Contacto";
			this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
			this.Text = "Contacto";
			this.Load += new System.EventHandler(this.Contacto_Load);
			((System.ComponentModel.ISupportInitialize)(this.grdCliente)).EndInit();
			this.ResumeLayout(false);

		}
		#endregion

		private void cboCalle_Enter(object sender, System.EventArgs e)
		{
			((ComboBox)sender).Height = 100;
			((ComboBox)sender).BringToFront();
		}

		private void Contacto_Load(object sender, System.EventArgs e)
		{
			grdCliente.DataSource = _contacto.ListaClientes;
		}

		private void btnCancelar_Click(object sender, System.EventArgs e)
		{
			this.DialogResult = DialogResult.Cancel;
			this.Close();
		}

		private void cargaDatos()
		{
			txtNombre.Text = _contacto.Nombre;
			txtTitulo.Text = _contacto.Titulo;
			txtDomicilio.Text = _contacto.Domicilio;
			txtHorario.Text = _contacto.Horario;
			txtNombre.Text = _contacto.Nombre;
			txtObservaciones.Text = _contacto.Observaciones;
			txtOrganizacion.Text = _contacto.Organizacion;
			txtTitulo.Text = _contacto.Titulo;
			telefono1.Lada = _contacto.Lada;
			telefono1.NumeroTelefono = _contacto.Telefono;
			telefono1.Extension = _contacto.Extension;
			telefonoCelular1.Telefono = _contacto.Celular;
			eMail1.CorreoElectronico = _contacto.CorreoElectronico;

			dataBindComboPuesto();

			cboPuesto.SelectedValue = _contacto.Puesto;
		}

		private void btnAceptar_Click(object sender, System.EventArgs e)
		{
			if (valitateInput())
				return;

			assignData();
			try
			{
				_contacto.AltaContacto();
				MessageBox.Show("Contacto registrado correctamente", "Contacto: " + _contacto.Contacto.ToString(),
					MessageBoxButtons.OK, MessageBoxIcon.Information);
				this.DialogResult = DialogResult.OK;
			}
			catch (Exception ex)
			{
				MessageBox.Show("Ha ocurrido un error:" + (char)13 + ex.ToString(), this.Text, MessageBoxButtons.OK, MessageBoxIcon.Error);
			}
		}

		private void btnAceptar1_Click(object sender, System.EventArgs e)
		{
			if (valitateInput())
				return;

			assignData();
			try
			{
				_contacto.ModificacionContacto(_editable);
				MessageBox.Show("Contacto actualizado correctamente", "Contacto: " + _contacto.Contacto.ToString(),
					MessageBoxButtons.OK, MessageBoxIcon.Information);
				this.DialogResult = DialogResult.OK;
			}
			catch (Exception ex)
			{
				MessageBox.Show("Ha ocurrido un error:" + (char)13 + ex.ToString(), this.Text, MessageBoxButtons.OK, MessageBoxIcon.Error);
			}
		}

		private void assignData()
		{
			_contacto.Celular = telefonoCelular1.Telefono;
			_contacto.CorreoElectronico = eMail1.CorreoElectronico;
			_contacto.Domicilio = txtDomicilio.Text;
			_contacto.Extension = telefono1.Extension;
			_contacto.FCumpleaños = dtpFCumpleanios.Value.Date;
			_contacto.Horario = txtHorario.Text;
			_contacto.Lada = telefono1.Lada;
			_contacto.Nombre = txtNombre.Text;
			_contacto.Observaciones = txtObservaciones.Text;
			_contacto.Puesto = Convert.ToInt16(cboPuesto.SelectedValue);
			_contacto.DescripcionPuesto = cboPuesto.Text;
			_contacto.Telefono = telefono1.NumeroTelefono;
			_contacto.Titulo = txtTitulo.Text;
			_contacto.Organizacion = txtOrganizacion.Text;
		}

		private void btnClientesAsociados_Click(object sender, System.EventArgs e)
		{
			SigaMetClasses.BusquedaCliente frmCliente = new SigaMetClasses.BusquedaCliente(true, true, false, false, string.Empty,
				0, false, false, false, dsCatalogos, URLGateway:_urlGateway, Modulo:_modulo, CadCon:_cadenaConexion);
			if (frmCliente.ShowDialog() == DialogResult.OK)
			{
				try
				{
					_contacto.AddCliente(frmCliente.Cliente, 
						1, Convert.ToString(dsCatalogos.Tables[1].Select("TipoContacto = 1")[0][1]));
				}
				catch (System.Data.ConstraintException ex)
				{
					MessageBox.Show(ex.Message, this.Text, MessageBoxButtons.OK, MessageBoxIcon.Exclamation);
				}
				catch (Exception ex)
				{
					MessageBox.Show("Ha ocurrido un error:" + (char)13 + ex.ToString(), this.Text, MessageBoxButtons.OK, MessageBoxIcon.Error);
				}
			}
		}

		private void eMail1_ValidatedMail(object sender, System.EventArgs e)
		{
			MessageBox.Show("La dirección de correo: " + ((EMail)sender).CorreoElectronico + (char)13 +
				"proporcionada no es válida", this.Text, MessageBoxButtons.OK, MessageBoxIcon.Exclamation);		
		}

		private void grdCliente_CurrentCellChanged(object sender, System.EventArgs e)
		{
			grdCliente.Controls.Clear();
			if (grdCliente.CurrentCell.ColumnNumber == 2)
			{
				ComboBox cbo = new ComboBox();

				cbo.Width = grdCliente.GetCellBounds(grdCliente.CurrentCell).Width;
				cbo.Height = grdCliente.GetCellBounds(grdCliente.CurrentCell).Height - 1;
				cbo.Top = grdCliente.GetCellBounds(grdCliente.CurrentCell).Top;
				cbo.Left = grdCliente.GetCellBounds(grdCliente.CurrentCell).Left;

				cbo.DataSource = dsCatalogos.Tables[1];
				cbo.ValueMember = "TipoContacto";
				cbo.DisplayMember = "Descripcion";
				cbo.DropDownStyle = ComboBoxStyle.DropDownList;
				

				cbo.SelectedIndexChanged += new EventHandler(cboSelectedIndex);
				grdCliente.Controls.Add(cbo);
			}
		}

		private void cboSelectedIndex(object sender, System.EventArgs e)
		{
			System.Data.DataRow dr = _contacto.ListaClientes.Rows.Find(grdCliente[grdCliente.CurrentRowIndex, 0]);
			if (dr != null)
			{
				dr.BeginEdit();
				dr["TipoContacto"] = ((ComboBox)sender).SelectedValue;
				dr["TipoContactoDescripcion"] = ((ComboBox)sender).Text;
				dr.EndEdit();
			}
		}

		private void grdCliente_Leave(object sender, System.EventArgs e)
		{
			grdCliente.Controls.Clear();
		}

		private void cboPuesto_TextChanged(object sender, System.EventArgs e)
		{
			string Calle  = cboPuesto.Text;
			cboPuesto.SelectedIndex = cboPuesto.FindString(Calle);
		}

		private void dataBindComboPuesto()
		{
			cboPuesto.DataSource = dsCatalogos.Tables[0];
			cboPuesto.ValueMember = "ContactoPuesto";
			cboPuesto.DisplayMember = "Descripcion";
		}

		private void btnModificar_Click(object sender, System.EventArgs e)
		{
			_editable = true;
			btnModificar.Enabled = false;
			activarParaEditar(!_editable);
		}

		private void activarParaEditar(bool Activar)
		{
			txtDomicilio.ReadOnly = Activar;
			txtHorario.ReadOnly = Activar;
			txtNombre.ReadOnly = Activar;
			txtObservaciones.ReadOnly = Activar;
			txtOrganizacion.ReadOnly = Activar;
			txtTitulo.ReadOnly = Activar;
			cboPuesto.Enabled = !Activar;
			telefono1.ReadOnly = Activar;
			telefonoCelular1.ReadOnly = Activar;
			eMail1.ReadOnly = Activar;
			dtpFCumpleanios.Enabled = !Activar;
			btnClientesAsociados.Enabled = !Activar;

			if (!Activar)
				this.grdCliente.CurrentCellChanged += new System.EventHandler(this.grdCliente_CurrentCellChanged);
			else
				this.grdCliente.CurrentCellChanged -= new System.EventHandler(this.grdCliente_CurrentCellChanged);
		}

		private bool valitateInput()
		{
			bool required = false;
			foreach(Control ctrl in this.Controls)
			{
				if (ctrl.GetType() == typeof(TextBox))// && (((TextBox)ctrl).Tag.ToString() == "required"))
					if (((ctrl.Tag != null) && (ctrl.Tag.ToString() == "required"))
						&& !(((TextBox)ctrl).Text.Length > 0))
					{
						MessageBox.Show("Este valor es requerido", "Valor requerido", MessageBoxButtons.OK, MessageBoxIcon.Exclamation);
						required = true;
						((TextBox)ctrl).Focus();
						break;
					}
			}
			return required;
		}

		private void menuItem2_Click(object sender, System.EventArgs e)
		{
			System.Data.DataRow dr = _contacto.ListaClientes.Rows.Find(grdCliente[grdCliente.CurrentRowIndex, 0]);
			if (dr != null)
			{
				_contacto.ListaClientes.Rows.Remove(dr);
			}
		}
	}
}
