using System;
using System.Drawing;
using System.Collections;
using System.ComponentModel;
using System.Windows.Forms;

namespace AsignacionMultiple
{
	/// <summary>
	/// Summary description for AsignacionClientePadre.
	/// </summary>
	public class AsignacionClientePadre : System.Windows.Forms.Form
	{
		#region Windows autogenerated code
		internal System.Windows.Forms.GroupBox grdDatosCliente;
		internal System.Windows.Forms.Label lblTelCasa;
		internal System.Windows.Forms.Label Label3;
		internal System.Windows.Forms.Label lblCliente;
		internal System.Windows.Forms.Label Label4;
		internal System.Windows.Forms.Label Label1;
		internal System.Windows.Forms.Label Label5;
		internal System.Windows.Forms.Label lblDireccion;
		internal System.Windows.Forms.Label lblRuta;
		internal System.Windows.Forms.Label Label12;
		internal System.Windows.Forms.Label lblCelula;
		private CustGrd.vwGrd vwGrd1;
		#endregion
		/// <summary>
		/// Required designer variable.
		/// </summary>
		private System.ComponentModel.Container components = null;

		private int _clientePadre;
		private System.Windows.Forms.StatusBar statusBar1;
		private System.Windows.Forms.StatusBarPanel statusBarPanel1;
		private AsignacionMultiple.ClientePadreCyC clientePadreCyC;
		internal System.Windows.Forms.Label label2;
		private AsignacionMultiple.ClientePadreEdificio clientePadreEdificio;
		
		public AsignacionClientePadre(System.Data.SqlClient.SqlConnection Connection,
			int ClientePadre)
		{
			InitializeComponent();

			this.Text = "Clientes relacionados";

			_clientePadre = ClientePadre;
			clientePadreCyC = new AsignacionMultiple.ClientePadreCyC(Connection, ClientePadre);
			cargaDatos();
		}

		public AsignacionClientePadre(System.Data.SqlClient.SqlConnection Connection,
			int ClientePadreEdificio, bool Edificio)
		{
			InitializeComponent();

			this.Text = "Clientes relacionados Edificios Administrados";

			_clientePadre = ClientePadreEdificio;
			clientePadreEdificio = new AsignacionMultiple.ClientePadreEdificio(Connection, ClientePadreEdificio);
			cargaDatosEdificio();
		}

		private void cargaDatos()
		{
			vwGrd1.DataSource = clientePadreCyC.ClientesHijo;
			vwGrd1.AutoColumnHeader();
			vwGrd1.DataAdd();

			lblCliente.Text = clientePadreCyC.NClientePadre.ToString().Trim() + " - " + clientePadreCyC.Nombre.Trim();
			lblRuta.Text = clientePadreCyC.CelulaClientePadre.ToString().Trim();
			lblCelula.Text = clientePadreCyC.RutaClientePadre.ToString().Trim();
			lblTelCasa.Text = clientePadreCyC.TelCtePadre.Trim();
			lblDireccion.Text = clientePadreCyC.Direccion.ToString().Trim();
		}

		private void cargaDatosEdificio()
		{
			vwGrd1.DataSource = clientePadreEdificio.ClientesHijo;
			vwGrd1.AutoColumnHeader();
			vwGrd1.DataAdd();

			lblCliente.Text = clientePadreEdificio.NClientePadre.ToString().Trim() +
				" - " + clientePadreEdificio.Nombre.Trim();
			lblRuta.Text = clientePadreEdificio.CelulaClientePadre.ToString().Trim();
			lblCelula.Text = clientePadreEdificio.RutaClientePadre.ToString().Trim();
			lblTelCasa.Text = clientePadreEdificio.TelCtePadre.Trim();
			lblDireccion.Text = clientePadreEdificio.Direccion.ToString().Trim();
		}


		/// <summary>
		/// Clean up any resources being used.
		/// </summary>
		protected override void Dispose( bool disposing )
		{
			if( disposing )
			{
				if(components != null)
				{
					components.Dispose();
				}
			}
			base.Dispose( disposing );
		}

		#region Windows Form Designer generated code
		/// <summary>
		/// Required method for Designer support - do not modify
		/// the contents of this method with the code editor.
		/// </summary>
		private void InitializeComponent()
		{
			this.grdDatosCliente = new System.Windows.Forms.GroupBox();
			this.lblCliente = new System.Windows.Forms.Label();
			this.Label4 = new System.Windows.Forms.Label();
			this.Label1 = new System.Windows.Forms.Label();
			this.Label5 = new System.Windows.Forms.Label();
			this.lblDireccion = new System.Windows.Forms.Label();
			this.lblRuta = new System.Windows.Forms.Label();
			this.Label12 = new System.Windows.Forms.Label();
			this.lblCelula = new System.Windows.Forms.Label();
			this.lblTelCasa = new System.Windows.Forms.Label();
			this.Label3 = new System.Windows.Forms.Label();
			this.vwGrd1 = new CustGrd.vwGrd();
			this.statusBar1 = new System.Windows.Forms.StatusBar();
			this.statusBarPanel1 = new System.Windows.Forms.StatusBarPanel();
			this.label2 = new System.Windows.Forms.Label();
			this.grdDatosCliente.SuspendLayout();
			((System.ComponentModel.ISupportInitialize)(this.statusBarPanel1)).BeginInit();
			this.SuspendLayout();
			// 
			// grdDatosCliente
			// 
			this.grdDatosCliente.Controls.AddRange(new System.Windows.Forms.Control[] {
																						  this.lblCliente,
																						  this.Label4,
																						  this.Label1,
																						  this.Label5,
																						  this.lblDireccion,
																						  this.lblRuta,
																						  this.Label12,
																						  this.lblCelula,
																						  this.lblTelCasa,
																						  this.Label3});
			this.grdDatosCliente.Location = new System.Drawing.Point(4, 4);
			this.grdDatosCliente.Name = "grdDatosCliente";
			this.grdDatosCliente.Size = new System.Drawing.Size(776, 94);
			this.grdDatosCliente.TabIndex = 41;
			this.grdDatosCliente.TabStop = false;
			this.grdDatosCliente.Text = "Datos del cliente";
			// 
			// lblCliente
			// 
			this.lblCliente.BackColor = System.Drawing.Color.WhiteSmoke;
			this.lblCliente.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((System.Byte)(0)));
			this.lblCliente.ForeColor = System.Drawing.Color.MediumBlue;
			this.lblCliente.Location = new System.Drawing.Point(88, 16);
			this.lblCliente.Name = "lblCliente";
			this.lblCliente.Size = new System.Drawing.Size(680, 21);
			this.lblCliente.TabIndex = 18;
			this.lblCliente.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
			// 
			// Label4
			// 
			this.Label4.AutoSize = true;
			this.Label4.Location = new System.Drawing.Point(432, 68);
			this.Label4.Name = "Label4";
			this.Label4.Size = new System.Drawing.Size(40, 13);
			this.Label4.TabIndex = 26;
			this.Label4.Text = "Célula:";
			this.Label4.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
			// 
			// Label1
			// 
			this.Label1.AutoSize = true;
			this.Label1.Location = new System.Drawing.Point(8, 19);
			this.Label1.Name = "Label1";
			this.Label1.Size = new System.Drawing.Size(43, 13);
			this.Label1.TabIndex = 23;
			this.Label1.Text = "Cliente:";
			this.Label1.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
			// 
			// Label5
			// 
			this.Label5.AutoSize = true;
			this.Label5.Location = new System.Drawing.Point(600, 68);
			this.Label5.Name = "Label5";
			this.Label5.Size = new System.Drawing.Size(31, 13);
			this.Label5.TabIndex = 27;
			this.Label5.Text = "Ruta:";
			this.Label5.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
			// 
			// lblDireccion
			// 
			this.lblDireccion.BackColor = System.Drawing.Color.WhiteSmoke;
			this.lblDireccion.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((System.Byte)(0)));
			this.lblDireccion.Location = new System.Drawing.Point(88, 40);
			this.lblDireccion.Name = "lblDireccion";
			this.lblDireccion.Size = new System.Drawing.Size(680, 21);
			this.lblDireccion.TabIndex = 30;
			this.lblDireccion.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
			// 
			// lblRuta
			// 
			this.lblRuta.BackColor = System.Drawing.Color.WhiteSmoke;
			this.lblRuta.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((System.Byte)(0)));
			this.lblRuta.Location = new System.Drawing.Point(656, 64);
			this.lblRuta.Name = "lblRuta";
			this.lblRuta.Size = new System.Drawing.Size(112, 21);
			this.lblRuta.TabIndex = 21;
			this.lblRuta.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
			// 
			// Label12
			// 
			this.Label12.AutoSize = true;
			this.Label12.Location = new System.Drawing.Point(8, 43);
			this.Label12.Name = "Label12";
			this.Label12.Size = new System.Drawing.Size(55, 13);
			this.Label12.TabIndex = 31;
			this.Label12.Text = "Dirección:";
			this.Label12.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
			// 
			// lblCelula
			// 
			this.lblCelula.BackColor = System.Drawing.Color.WhiteSmoke;
			this.lblCelula.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((System.Byte)(0)));
			this.lblCelula.Location = new System.Drawing.Point(480, 64);
			this.lblCelula.Name = "lblCelula";
			this.lblCelula.Size = new System.Drawing.Size(112, 21);
			this.lblCelula.TabIndex = 20;
			this.lblCelula.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
			// 
			// lblTelCasa
			// 
			this.lblTelCasa.BackColor = System.Drawing.Color.WhiteSmoke;
			this.lblTelCasa.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((System.Byte)(0)));
			this.lblTelCasa.Location = new System.Drawing.Point(88, 64);
			this.lblTelCasa.Name = "lblTelCasa";
			this.lblTelCasa.Size = new System.Drawing.Size(144, 21);
			this.lblTelCasa.TabIndex = 22;
			this.lblTelCasa.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
			// 
			// Label3
			// 
			this.Label3.AutoSize = true;
			this.Label3.Location = new System.Drawing.Point(8, 68);
			this.Label3.Name = "Label3";
			this.Label3.Size = new System.Drawing.Size(51, 13);
			this.Label3.TabIndex = 25;
			this.Label3.Text = "Teléfono:";
			this.Label3.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
			// 
			// vwGrd1
			// 
			this.vwGrd1.ColumnMargin = 20;
			this.vwGrd1.Location = new System.Drawing.Point(4, 124);
			this.vwGrd1.Name = "vwGrd1";
			this.vwGrd1.Size = new System.Drawing.Size(776, 388);
			this.vwGrd1.TabIndex = 42;
			this.vwGrd1.View = System.Windows.Forms.View.Details;
			this.vwGrd1.ListViewContentChanged += new CustGrd._listViewContentChanged(this.vwGrd1_ListViewContentChanged);
			// 
			// statusBar1
			// 
			this.statusBar1.Location = new System.Drawing.Point(0, 515);
			this.statusBar1.Name = "statusBar1";
			this.statusBar1.Panels.AddRange(new System.Windows.Forms.StatusBarPanel[] {
																						  this.statusBarPanel1});
			this.statusBar1.ShowPanels = true;
			this.statusBar1.Size = new System.Drawing.Size(784, 22);
			this.statusBar1.TabIndex = 43;
			// 
			// statusBarPanel1
			// 
			this.statusBarPanel1.Width = 790;
			// 
			// label2
			// 
			this.label2.BackColor = System.Drawing.Color.WhiteSmoke;
			this.label2.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
			this.label2.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
			this.label2.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((System.Byte)(0)));
			this.label2.ForeColor = System.Drawing.Color.DarkBlue;
			this.label2.Location = new System.Drawing.Point(4, 100);
			this.label2.Name = "label2";
			this.label2.Size = new System.Drawing.Size(120, 21);
			this.label2.TabIndex = 32;
			this.label2.Text = "Clientes asignados";
			this.label2.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
			// 
			// AsignacionClientePadre
			// 
			this.AutoScaleBaseSize = new System.Drawing.Size(5, 13);
			this.ClientSize = new System.Drawing.Size(784, 537);
			this.Controls.AddRange(new System.Windows.Forms.Control[] {
																		  this.statusBar1,
																		  this.vwGrd1,
																		  this.grdDatosCliente,
																		  this.label2});
			this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedDialog;
			this.MaximizeBox = false;
			this.MinimizeBox = false;
			this.Name = "AsignacionClientePadre";
			this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
			this.Text = "AsignacionClientePadre";
			this.Load += new System.EventHandler(this.AsignacionClientePadre_Load);
			this.grdDatosCliente.ResumeLayout(false);
			((System.ComponentModel.ISupportInitialize)(this.statusBarPanel1)).EndInit();
			this.ResumeLayout(false);

		}
		#endregion

		private void vwGrd1_ListViewContentChanged(object sender, System.EventArgs e)
		{
			statusBarPanel1.Text = vwGrd1.Items.Count.ToString() + " clientes" ;
		}

		private void AsignacionClientePadre_Load(object sender, System.EventArgs e)
		{
			vwGrd1_ListViewContentChanged(null, null);
		}
	}
}
