//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GasMetropolitano.Runtime.DynamicsCRMActualizacionSaldo {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="resultado", Namespace="http://schemas.datacontract.org/2004/07/WCF_ITSSA_Saldos.Model")]
    [System.SerializableAttribute()]
    public partial class resultado : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExcepcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ID_PedidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObservacionesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool OperacionExitosaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Excepcion {
            get {
                return this.ExcepcionField;
            }
            set {
                if ((object.ReferenceEquals(this.ExcepcionField, value) != true)) {
                    this.ExcepcionField = value;
                    this.RaisePropertyChanged("Excepcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ID_Pedido {
            get {
                return this.ID_PedidoField;
            }
            set {
                if ((this.ID_PedidoField.Equals(value) != true)) {
                    this.ID_PedidoField = value;
                    this.RaisePropertyChanged("ID_Pedido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Observaciones {
            get {
                return this.ObservacionesField;
            }
            set {
                if ((object.ReferenceEquals(this.ObservacionesField, value) != true)) {
                    this.ObservacionesField = value;
                    this.RaisePropertyChanged("Observaciones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool OperacionExitosa {
            get {
                return this.OperacionExitosaField;
            }
            set {
                if ((this.OperacionExitosaField.Equals(value) != true)) {
                    this.OperacionExitosaField = value;
                    this.RaisePropertyChanged("OperacionExitosa");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DynamicsCRMActualizacionSaldo.WCF_ITSSA_Saldos")]
    public interface WCF_ITSSA_Saldos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WCF_ITSSA_Saldos/UpdateSaldos", ReplyAction="http://tempuri.org/WCF_ITSSA_Saldos/UpdateSaldosResponse")]
        GasMetropolitano.Runtime.DynamicsCRMActualizacionSaldo.resultado UpdateSaldos(int ID, decimal Saldo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WCF_ITSSA_Saldos/UpdateSaldos", ReplyAction="http://tempuri.org/WCF_ITSSA_Saldos/UpdateSaldosResponse")]
        System.Threading.Tasks.Task<GasMetropolitano.Runtime.DynamicsCRMActualizacionSaldo.resultado> UpdateSaldosAsync(int ID, decimal Saldo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WCF_ITSSA_SaldosChannel : GasMetropolitano.Runtime.DynamicsCRMActualizacionSaldo.WCF_ITSSA_Saldos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WCF_ITSSA_SaldosClient : System.ServiceModel.ClientBase<GasMetropolitano.Runtime.DynamicsCRMActualizacionSaldo.WCF_ITSSA_Saldos>, GasMetropolitano.Runtime.DynamicsCRMActualizacionSaldo.WCF_ITSSA_Saldos {
        
        public WCF_ITSSA_SaldosClient() {
        }
        
        public WCF_ITSSA_SaldosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WCF_ITSSA_SaldosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCF_ITSSA_SaldosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCF_ITSSA_SaldosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public GasMetropolitano.Runtime.DynamicsCRMActualizacionSaldo.resultado UpdateSaldos(int ID, decimal Saldo) {
            return base.Channel.UpdateSaldos(ID, Saldo);
        }
        
        public System.Threading.Tasks.Task<GasMetropolitano.Runtime.DynamicsCRMActualizacionSaldo.resultado> UpdateSaldosAsync(int ID, decimal Saldo) {
            return base.Channel.UpdateSaldosAsync(ID, Saldo);
        }
    }
}
