//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34209.
// 
#pragma warning disable 1591

namespace ReasignacionDePedidos.desarrollogm {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PedidoSoap", Namespace="http://tempuri.org/")]
    public partial class Pedido : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback BoletinarPedidoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaAutotanquesPorRutaYDiaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaPedidosPorAutotanqueFechaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReasignacionOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtieneCelulasOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtieneRutasPorCelulaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtieneAutotanquesPorRutaOperationCompleted;
        
        private System.Threading.SendOrPostCallback CancelaPedidoOperationCompleted;
        
        private System.Threading.SendOrPostCallback CancelaPedidoCallCenterOperationCompleted;
        
        private System.Threading.SendOrPostCallback RegistrarMensajeOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Pedido() {
            this.Url = global::ReasignacionDePedidos.Properties.Settings.Default.ReasignacionDePedidos_desarrollogm_Pedido;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event BoletinarPedidoCompletedEventHandler BoletinarPedidoCompleted;
        
        /// <remarks/>
        public event ConsultaAutotanquesPorRutaYDiaCompletedEventHandler ConsultaAutotanquesPorRutaYDiaCompleted;
        
        /// <remarks/>
        public event ConsultaPedidosPorAutotanqueFechaCompletedEventHandler ConsultaPedidosPorAutotanqueFechaCompleted;
        
        /// <remarks/>
        public event ReasignacionCompletedEventHandler ReasignacionCompleted;
        
        /// <remarks/>
        public event ObtieneCelulasCompletedEventHandler ObtieneCelulasCompleted;
        
        /// <remarks/>
        public event ObtieneRutasPorCelulaCompletedEventHandler ObtieneRutasPorCelulaCompleted;
        
        /// <remarks/>
        public event ObtieneAutotanquesPorRutaCompletedEventHandler ObtieneAutotanquesPorRutaCompleted;
        
        /// <remarks/>
        public event CancelaPedidoCompletedEventHandler CancelaPedidoCompleted;
        
        /// <remarks/>
        public event CancelaPedidoCallCenterCompletedEventHandler CancelaPedidoCallCenterCompleted;
        
        /// <remarks/>
        public event RegistrarMensajeCompletedEventHandler RegistrarMensajeCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BoletinarPedido", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool BoletinarPedido(string Estacion, string Usuario, string PedidoReferencia, bool EsProgramacion, int Autotanque, string IdEstacionSGC, string Observaciones) {
            object[] results = this.Invoke("BoletinarPedido", new object[] {
                        Estacion,
                        Usuario,
                        PedidoReferencia,
                        EsProgramacion,
                        Autotanque,
                        IdEstacionSGC,
                        Observaciones});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void BoletinarPedidoAsync(string Estacion, string Usuario, string PedidoReferencia, bool EsProgramacion, int Autotanque, string IdEstacionSGC, string Observaciones) {
            this.BoletinarPedidoAsync(Estacion, Usuario, PedidoReferencia, EsProgramacion, Autotanque, IdEstacionSGC, Observaciones, null);
        }
        
        /// <remarks/>
        public void BoletinarPedidoAsync(string Estacion, string Usuario, string PedidoReferencia, bool EsProgramacion, int Autotanque, string IdEstacionSGC, string Observaciones, object userState) {
            if ((this.BoletinarPedidoOperationCompleted == null)) {
                this.BoletinarPedidoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBoletinarPedidoOperationCompleted);
            }
            this.InvokeAsync("BoletinarPedido", new object[] {
                        Estacion,
                        Usuario,
                        PedidoReferencia,
                        EsProgramacion,
                        Autotanque,
                        IdEstacionSGC,
                        Observaciones}, this.BoletinarPedidoOperationCompleted, userState);
        }
        
        private void OnBoletinarPedidoOperationCompleted(object arg) {
            if ((this.BoletinarPedidoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BoletinarPedidoCompleted(this, new BoletinarPedidoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultaAutotanquesPorRutaYDia", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ConsultaAutotanquesPorRutaYDia(string Estacion, int Ruta, System.DateTime FechaI, System.DateTime FechaF) {
            object[] results = this.Invoke("ConsultaAutotanquesPorRutaYDia", new object[] {
                        Estacion,
                        Ruta,
                        FechaI,
                        FechaF});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaAutotanquesPorRutaYDiaAsync(string Estacion, int Ruta, System.DateTime FechaI, System.DateTime FechaF) {
            this.ConsultaAutotanquesPorRutaYDiaAsync(Estacion, Ruta, FechaI, FechaF, null);
        }
        
        /// <remarks/>
        public void ConsultaAutotanquesPorRutaYDiaAsync(string Estacion, int Ruta, System.DateTime FechaI, System.DateTime FechaF, object userState) {
            if ((this.ConsultaAutotanquesPorRutaYDiaOperationCompleted == null)) {
                this.ConsultaAutotanquesPorRutaYDiaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaAutotanquesPorRutaYDiaOperationCompleted);
            }
            this.InvokeAsync("ConsultaAutotanquesPorRutaYDia", new object[] {
                        Estacion,
                        Ruta,
                        FechaI,
                        FechaF}, this.ConsultaAutotanquesPorRutaYDiaOperationCompleted, userState);
        }
        
        private void OnConsultaAutotanquesPorRutaYDiaOperationCompleted(object arg) {
            if ((this.ConsultaAutotanquesPorRutaYDiaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaAutotanquesPorRutaYDiaCompleted(this, new ConsultaAutotanquesPorRutaYDiaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultaPedidosPorAutotanqueFecha", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ConsultaPedidosPorAutotanqueFecha(string Estacion, int Autotanque, System.DateTime FechaCompromiso) {
            object[] results = this.Invoke("ConsultaPedidosPorAutotanqueFecha", new object[] {
                        Estacion,
                        Autotanque,
                        FechaCompromiso});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaPedidosPorAutotanqueFechaAsync(string Estacion, int Autotanque, System.DateTime FechaCompromiso) {
            this.ConsultaPedidosPorAutotanqueFechaAsync(Estacion, Autotanque, FechaCompromiso, null);
        }
        
        /// <remarks/>
        public void ConsultaPedidosPorAutotanqueFechaAsync(string Estacion, int Autotanque, System.DateTime FechaCompromiso, object userState) {
            if ((this.ConsultaPedidosPorAutotanqueFechaOperationCompleted == null)) {
                this.ConsultaPedidosPorAutotanqueFechaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaPedidosPorAutotanqueFechaOperationCompleted);
            }
            this.InvokeAsync("ConsultaPedidosPorAutotanqueFecha", new object[] {
                        Estacion,
                        Autotanque,
                        FechaCompromiso}, this.ConsultaPedidosPorAutotanqueFechaOperationCompleted, userState);
        }
        
        private void OnConsultaPedidosPorAutotanqueFechaOperationCompleted(object arg) {
            if ((this.ConsultaPedidosPorAutotanqueFechaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaPedidosPorAutotanqueFechaCompleted(this, new ConsultaPedidosPorAutotanqueFechaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Reasignacion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Reasignacion(string Estacion, int AutotanqueDestino, System.Data.DataSet Datos, string Usuario, string IdEstacionSGC) {
            object[] results = this.Invoke("Reasignacion", new object[] {
                        Estacion,
                        AutotanqueDestino,
                        Datos,
                        Usuario,
                        IdEstacionSGC});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ReasignacionAsync(string Estacion, int AutotanqueDestino, System.Data.DataSet Datos, string Usuario, string IdEstacionSGC) {
            this.ReasignacionAsync(Estacion, AutotanqueDestino, Datos, Usuario, IdEstacionSGC, null);
        }
        
        /// <remarks/>
        public void ReasignacionAsync(string Estacion, int AutotanqueDestino, System.Data.DataSet Datos, string Usuario, string IdEstacionSGC, object userState) {
            if ((this.ReasignacionOperationCompleted == null)) {
                this.ReasignacionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReasignacionOperationCompleted);
            }
            this.InvokeAsync("Reasignacion", new object[] {
                        Estacion,
                        AutotanqueDestino,
                        Datos,
                        Usuario,
                        IdEstacionSGC}, this.ReasignacionOperationCompleted, userState);
        }
        
        private void OnReasignacionOperationCompleted(object arg) {
            if ((this.ReasignacionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReasignacionCompleted(this, new ReasignacionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtieneCelulas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ObtieneCelulas(string Estacion) {
            object[] results = this.Invoke("ObtieneCelulas", new object[] {
                        Estacion});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ObtieneCelulasAsync(string Estacion) {
            this.ObtieneCelulasAsync(Estacion, null);
        }
        
        /// <remarks/>
        public void ObtieneCelulasAsync(string Estacion, object userState) {
            if ((this.ObtieneCelulasOperationCompleted == null)) {
                this.ObtieneCelulasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtieneCelulasOperationCompleted);
            }
            this.InvokeAsync("ObtieneCelulas", new object[] {
                        Estacion}, this.ObtieneCelulasOperationCompleted, userState);
        }
        
        private void OnObtieneCelulasOperationCompleted(object arg) {
            if ((this.ObtieneCelulasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtieneCelulasCompleted(this, new ObtieneCelulasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtieneRutasPorCelula", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ObtieneRutasPorCelula(string Estacion, Celula Celula) {
            object[] results = this.Invoke("ObtieneRutasPorCelula", new object[] {
                        Estacion,
                        Celula});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ObtieneRutasPorCelulaAsync(string Estacion, Celula Celula) {
            this.ObtieneRutasPorCelulaAsync(Estacion, Celula, null);
        }
        
        /// <remarks/>
        public void ObtieneRutasPorCelulaAsync(string Estacion, Celula Celula, object userState) {
            if ((this.ObtieneRutasPorCelulaOperationCompleted == null)) {
                this.ObtieneRutasPorCelulaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtieneRutasPorCelulaOperationCompleted);
            }
            this.InvokeAsync("ObtieneRutasPorCelula", new object[] {
                        Estacion,
                        Celula}, this.ObtieneRutasPorCelulaOperationCompleted, userState);
        }
        
        private void OnObtieneRutasPorCelulaOperationCompleted(object arg) {
            if ((this.ObtieneRutasPorCelulaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtieneRutasPorCelulaCompleted(this, new ObtieneRutasPorCelulaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtieneAutotanquesPorRuta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ObtieneAutotanquesPorRuta(string Estacion, int Ruta) {
            object[] results = this.Invoke("ObtieneAutotanquesPorRuta", new object[] {
                        Estacion,
                        Ruta});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ObtieneAutotanquesPorRutaAsync(string Estacion, int Ruta) {
            this.ObtieneAutotanquesPorRutaAsync(Estacion, Ruta, null);
        }
        
        /// <remarks/>
        public void ObtieneAutotanquesPorRutaAsync(string Estacion, int Ruta, object userState) {
            if ((this.ObtieneAutotanquesPorRutaOperationCompleted == null)) {
                this.ObtieneAutotanquesPorRutaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtieneAutotanquesPorRutaOperationCompleted);
            }
            this.InvokeAsync("ObtieneAutotanquesPorRuta", new object[] {
                        Estacion,
                        Ruta}, this.ObtieneAutotanquesPorRutaOperationCompleted, userState);
        }
        
        private void OnObtieneAutotanquesPorRutaOperationCompleted(object arg) {
            if ((this.ObtieneAutotanquesPorRutaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtieneAutotanquesPorRutaCompleted(this, new ObtieneAutotanquesPorRutaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CancelaPedido", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool CancelaPedido(int Destino, string Estacion, int IDPedido) {
            object[] results = this.Invoke("CancelaPedido", new object[] {
                        Destino,
                        Estacion,
                        IDPedido});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CancelaPedidoAsync(int Destino, string Estacion, int IDPedido) {
            this.CancelaPedidoAsync(Destino, Estacion, IDPedido, null);
        }
        
        /// <remarks/>
        public void CancelaPedidoAsync(int Destino, string Estacion, int IDPedido, object userState) {
            if ((this.CancelaPedidoOperationCompleted == null)) {
                this.CancelaPedidoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCancelaPedidoOperationCompleted);
            }
            this.InvokeAsync("CancelaPedido", new object[] {
                        Destino,
                        Estacion,
                        IDPedido}, this.CancelaPedidoOperationCompleted, userState);
        }
        
        private void OnCancelaPedidoOperationCompleted(object arg) {
            if ((this.CancelaPedidoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CancelaPedidoCompleted(this, new CancelaPedidoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CancelaPedidoCallCenter", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool CancelaPedidoCallCenter(string Estacion, string PedidoReferencia) {
            object[] results = this.Invoke("CancelaPedidoCallCenter", new object[] {
                        Estacion,
                        PedidoReferencia});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CancelaPedidoCallCenterAsync(string Estacion, string PedidoReferencia) {
            this.CancelaPedidoCallCenterAsync(Estacion, PedidoReferencia, null);
        }
        
        /// <remarks/>
        public void CancelaPedidoCallCenterAsync(string Estacion, string PedidoReferencia, object userState) {
            if ((this.CancelaPedidoCallCenterOperationCompleted == null)) {
                this.CancelaPedidoCallCenterOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCancelaPedidoCallCenterOperationCompleted);
            }
            this.InvokeAsync("CancelaPedidoCallCenter", new object[] {
                        Estacion,
                        PedidoReferencia}, this.CancelaPedidoCallCenterOperationCompleted, userState);
        }
        
        private void OnCancelaPedidoCallCenterOperationCompleted(object arg) {
            if ((this.CancelaPedidoCallCenterCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CancelaPedidoCallCenterCompleted(this, new CancelaPedidoCallCenterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RegistrarMensaje", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool RegistrarMensaje(int Destino, string Estacion, string mensaje) {
            object[] results = this.Invoke("RegistrarMensaje", new object[] {
                        Destino,
                        Estacion,
                        mensaje});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void RegistrarMensajeAsync(int Destino, string Estacion, string mensaje) {
            this.RegistrarMensajeAsync(Destino, Estacion, mensaje, null);
        }
        
        /// <remarks/>
        public void RegistrarMensajeAsync(int Destino, string Estacion, string mensaje, object userState) {
            if ((this.RegistrarMensajeOperationCompleted == null)) {
                this.RegistrarMensajeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRegistrarMensajeOperationCompleted);
            }
            this.InvokeAsync("RegistrarMensaje", new object[] {
                        Destino,
                        Estacion,
                        mensaje}, this.RegistrarMensajeOperationCompleted, userState);
        }
        
        private void OnRegistrarMensajeOperationCompleted(object arg) {
            if ((this.RegistrarMensajeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RegistrarMensajeCompleted(this, new RegistrarMensajeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Celula {
        
        private ExtensionDataObject extensionDataField;
        
        private string descripcionField;
        
        private int idCelulaField;
        
        private string idEstacionSGCField;
        
        /// <remarks/>
        public ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        /// <remarks/>
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
        
        /// <remarks/>
        public int IdCelula {
            get {
                return this.idCelulaField;
            }
            set {
                this.idCelulaField = value;
            }
        }
        
        /// <remarks/>
        public string IdEstacionSGC {
            get {
                return this.idEstacionSGCField;
            }
            set {
                this.idEstacionSGCField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ExtensionDataObject {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void BoletinarPedidoCompletedEventHandler(object sender, BoletinarPedidoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BoletinarPedidoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BoletinarPedidoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void ConsultaAutotanquesPorRutaYDiaCompletedEventHandler(object sender, ConsultaAutotanquesPorRutaYDiaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaAutotanquesPorRutaYDiaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaAutotanquesPorRutaYDiaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void ConsultaPedidosPorAutotanqueFechaCompletedEventHandler(object sender, ConsultaPedidosPorAutotanqueFechaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaPedidosPorAutotanqueFechaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaPedidosPorAutotanqueFechaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void ReasignacionCompletedEventHandler(object sender, ReasignacionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReasignacionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReasignacionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void ObtieneCelulasCompletedEventHandler(object sender, ObtieneCelulasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtieneCelulasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtieneCelulasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void ObtieneRutasPorCelulaCompletedEventHandler(object sender, ObtieneRutasPorCelulaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtieneRutasPorCelulaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtieneRutasPorCelulaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void ObtieneAutotanquesPorRutaCompletedEventHandler(object sender, ObtieneAutotanquesPorRutaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtieneAutotanquesPorRutaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtieneAutotanquesPorRutaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void CancelaPedidoCompletedEventHandler(object sender, CancelaPedidoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CancelaPedidoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CancelaPedidoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void CancelaPedidoCallCenterCompletedEventHandler(object sender, CancelaPedidoCallCenterCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CancelaPedidoCallCenterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CancelaPedidoCallCenterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void RegistrarMensajeCompletedEventHandler(object sender, RegistrarMensajeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RegistrarMensajeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RegistrarMensajeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591